### ISSUE TITLE
Backup to standard output - works under Windows

### ISSUE THREAD

**Issue by tivnet** [loomchild/volume-backup#15]
Just tried with Docker on Windows 10 Pro. Got a perfect `.tar.bz2` archive.

    docker run -v my-volume:/volume --rm loomchild/volume-backup backup - > some_archive.tar.bz2

Thanks!

**Comment by loomchild** [comment]
Thanks for info. 

Are you using PowerShell or just standard CMD? Another user reported issues on Windows (https://github.com/loomchild/volume-backup/pull/7), but I cannot really test them since I don't have access to Windows machine.

**Comment by tivnet** [comment]
Standard CMD.

**Comment by loomchild** [comment]
OK thanks a lot. So then maybe the STDOUT/STDIN issue is related to PowerShell - would you be able to try with it? Also, could you confirm that extracting from STDIN works as well?

In the meantime, I will update the README (perhaps leaving a note to always verify the backups as a general best practice).

**Comment by tivnet** [comment]
Indeed, under PowerShell, the `backup - > some_archive.tar.bz2` produced a corrupted archive.

Several sources confirm that PowerShell cannot handle binary pipes. I've tried the `-encoding` option, and it failed, too.

**Comment by loomchild** [comment]
OK, thank you very much!

I have updated the README.
