### ISSUE TITLE
add some parallel compression type

### ISSUE THREAD

**Issue by luvarqpp** [loomchild/volume-backup#19]
I would like to use more cpu cores than single one.

Add possibility to use [pigz](https://zlib.net/pigz/), [zstd](https://github.com/facebook/zstd) or something similar.

PS: I like that your script is "auditable" in few minutes by simple reading. Consider, if feature like this one, does not make it "too long".

**Comment by loomchild** [comment]
I wasn't even aware these exist:)

I agree that I'd like to keep it simple. Would you like to propose a PR? If not, I will take a look at it a bit later.

**Comment by debuglevel** [comment]
That would be great! :-) To set a parallel compression method, additional tools (`pigz`, `pbzip2`, `pxz`) have to be installed and called by the `-I pxz` argument:
```
gz: tar -I pigz -cf tarball.tgz files
bz2: tar -I pbzip2 -cf tarball.tbz files
xz: tar -I pxz -cf tarball.txz files
```

**Comment by loomchild** [comment]
Thanks for the info!

I can try to integrate those if I find some time, or alternatively feel free to propose a PR.

**Comment by loomchild** [comment]
Zstd was just added by @ksurl https://github.com/loomchild/volume-backup/pull/36. I hope it solves the ticket - if not, please reopen.

**Comment by ksurl** [comment]
Zstd does support parallel compression with multithreading in the latest version but that version is not available in alpine yet. Pigz would be better if parallel is a must but zstd is pretty fast. Also since tar doesnt support passing flags to the compression program you'd have to use a pipe and change how the script calls it

**Comment by luvarqpp** [comment]
> Also since tar doesnt support passing flags to the compression program you'd have to use a pipe and change how the script calls it

IMHO it is possible to pass parameters. I use this approach:
```
tar --use-compress-program="pigz --best" -cf filesWithPrefixAsdf.tar.gz Asdf*
```

Note, that passed program have to support `-d` parameter (for decompression). If this is not the case (7za binary for example), you can have a look at simple wrapper approach on [stack owerflow](https://stackoverflow.com/a/27541309/11152683)

**Comment by loomchild** [comment]
BTW, I have just added an option `-x` to pass any arguments to Tar (see https://github.com/loomchild/volume-backup/issues/28). Perhaps this would be useful in such complex scenarios (unfortunately I can't verify as I am not using parallel compression)
