### ISSUE TITLE
Suggestion: Backup all volumes

### ISSUE THREAD

**Issue by modem7** [loomchild/volume-backup#21]
If we do docker volume ls -q, we're able to see all volumes currently on Docker.

If we can do something like

docker container stop $(docker container ls -aq)
backup command with docker volume -q as a variable
docker container start $(docker container ls -aq)

We should be able to stop all containers, backup their respective volumes, and restart them.

Thoughts?

**Comment by loomchild** [comment]
Yes, that should work. Or you could stop all containers and list all volumes.

What is your suggestion?

**Comment by modem7** [comment]
Basically was wondering if there's a single command we can run (well, after we stop the containers  anyway), so backup all the volumes. 

Currently I'm doing one line per volume, and was curious if there was a more efficient way of doing things! Unfortunately I'm rather new to docker, so not too experienced in all the potential commands

**Comment by loomchild** [comment]
Really sorry for late reply.

Sorry, backing-up all volumes is a bit out of the scope for this tool.

Take a look at suggestion here, maybe you'll find it useful: https://github.com/loomchild/volume-backup/issues/16

Alternatively write a simple `bash` script to list all volumes via `docker volume ls` and iterate over them using a for loop.
