### ISSUE TITLE
Restoring file gives invalid magic + short read

### ISSUE THREAD

**Issue by modem7** [loomchild/volume-backup#22]
Method to reproduce: 
Backup:
1. Stop container
2. Backup with sudo docker run -v Tautulli:/volume --rm loomchild/volume-backup backup - > /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/Tautulli.tar

Restore:
cat /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/Tautulli.tar | docker run -i -v Tautulli:/volume --rm loomchild/volume-backup restore -
tar: invalid magic
tar: short read

Not quite sure what I'm doing wrong here!

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:52 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:19:08 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by loomchild** [comment]
Note that by default the archive will be .bz2, so your file name should end with .tar. If you want to use plain tar, specify -c 0 option on backup and restore. However, this shouldn't matter IMHO.

Could you check what is in the created archive file and try to extract it?

**Comment by modem7** [comment]
Each of the archives end in .tar currently, and inside the tar all the files I'd expect to see in the volume are indeed there. 

So not quite sure where I'm going wrong, and I'm pretty sure it's a user error on this one!

**Comment by ffminus** [comment]
I had the same issue, caused by me forgetting the interactive process flag (-i).
Adding it back fixed the problem.

**Comment by modem7** [comment]
> 
> 
> I had the same issue, caused by me forgetting the interactive process flag (-i).
> Adding it back fixed the problem.

Tried that unfortunately!

> $ cat /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/DDClient.tar | docker run -i -v DDClient:/volume --rm loomchild/volume-backup restore -
> tar: invalid magic
> tar: short read

**Comment by ffminus** [comment]
Yeah, it didn't work for another volume for me too.
Still looking for a fix.

**Comment by loomchild** [comment]
Really sorry for late reply. 

The restore process expects `.tar.bz2` by default. Try passing `-c 0` option during restore as mentioned in the first comment:

```cat /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/DDClient.tar | docker run -i -v DDClient:/volume --rm loomchild/volume-backup restore -c 0 -```

**Comment by loomchild** [comment]
Please let me know if you still experience the issue and if you do please describe steps to reproduce (both back-up and restore).

**Comment by modem7** [comment]
Sorry for the long reply, been off ill! 

Hmmm, still getting the same error. I tried going back to the expected 'bz2' to reduce any additional variables.

Backup command:
sudo docker run -v NZBHydra2:/volume --rm loomchild/volume-backup backup -c gz - > /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/NZBHydra2.tar.bz2

Restore command: 
sudo cat /var/hda/files/drives/drive12/downloads/Backups/dockerbackup/NZBHydra2.tar.bz2 | docker run -i -v NZBHydra2:/volume --rm loomchild/volume-backup restore -

Error:
bzip2: invalid magic
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
read unix @->/run/docker.sock: read: connection reset by peer


It did however, create a volume, but no data inside it.

**Comment by loomchild** [comment]
Hi,

I see that in your backup command you are using gz compression instead of bz2 - could you try correcting it (either by removing `-c gz` parameter or specifying `-c bz2`)?

Also please make sure that you are using the latest version of the utility by pulling the latest image via
`docker pull loomchild/volume-backup`.

**Comment by modem7** [comment]
Looks like I had the wrong command! 

All working as expected!

Thank you very much and apologies for the ID10T!

**Comment by loomchild** [comment]
No worries, I am glad it worked and sorry for my delayed replies.
