### ISSUE TITLE
add verbose mode to backup

### ISSUE THREAD

**Issue by metronlab-it** [loomchild/volume-backup#24]
Is there any way to add a “verbose” option to the backup/restore, or a status indicator? A few times I’ve been backing up a big volume and with no output, I didn’t know if the process was stalled, crashed or just slow and not finished yet… it doesn't even need to be a percentage indicator, just some sort of indication that the process is still running and hasn't crashed, a stdout of a '.' every 10/20/30secs even would do....

**Comment by loomchild** [comment]
Thanks for suggestion, I will look into this ASAP, in the coming weeks (sorry, running a bit behind with everything).

**Comment by loomchild** [comment]
It should be easy to do via `--checkpoint=.1000` tar option: https://www.gnu.org/software/tar/manual/html_section/tar_25.html, https://www.gnu.org/software/tar/manual/html_section/tar_26.html

Be sure to check that it correctly writes the output to stderr to avoid corrupting volumes when redirecting stdout.

**Comment by loomchild** [comment]
Done - try `-v` flag (remember to pull the latest volume-backup image - see README)
