### ISSUE TITLE
restore from stdin expects bzip2 input

### ISSUE THREAD

**Issue by joequant** [loomchild/volume-backup#26]
The stdout backup appears to generate an uncompressed output, but the stdin input requires the input as bz2.  This seems inconsistent and confusing.

**Comment by loomchild** [comment]
I thought that by default stdout backup generates bz2. Could you share the commands you are executing for backup and restore?

**Comment by joequant** [comment]
Ahhh  i see what's going on....

The command I'm using to do the backup looks like 

docker run -v volume:/volume --rm loomchild/volume-backup backup -c xz 

Which generates a plain xz file....

**Comment by loomchild** [comment]
:+1: - I am glad it worked for you.
