### ISSUE TITLE
 add option to include arbitrary tar options

### ISSUE THREAD

**Issue by joequant** [loomchild/volume-backup#28]
Should add an option to allow user to include arbitrary tar options.  This would be useful for adding the ability to do things like incremental backups.

**Comment by loomchild** [comment]
Hi Joseph, thanks for reaching out, I can take a look into this a bit later. In the meantime, feel free to propose a pull request.

**Comment by loomchild** [comment]
Done via `-x` parameter. Thanks for your suggestion and sorry for delay.
