### ISSUE TITLE
include options for no-clobber

### ISSUE THREAD

**Issue by joequant** [loomchild/volume-backup#29]
Should have an option to quit if there is an existing volume of the same name.

**Comment by loomchild** [comment]
Not sure if I understand - you mean avoid deleting a volume when restoring?

I don't think I can check if volume exists (the utility is running inside Docker), but I could probably check whether volume is not-empty and fail in this case. Would that work for you?

**Comment by joequant** [comment]
What I had in mind was an option that would issue an error if a volume
already exists rather than overwriting.  The purpose of the
script is to just provide a protection to make it more difficult to
accidentally overwrite a volume.

**Comment by loomchild** [comment]
OK, thanks, it's clear. As said I can't directly check if volume exists, since there's no such command in Docker and my utility runs inside Docker. What I can do is to check if volume is not empty, and if that's the case, then I can abort the restore operation.

**Comment by loomchild** [comment]
Done, now restore operation will fail if target volume is not empty. This can be overridden via force `-f` flag.
