### ISSUE TITLE
Store backups in S3

### ISSUE THREAD

**Issue by JDiPierro** [loomchild/volume-backup#3]
Would be awesome to provide the container with AWS credentials and a bucket and have it upload backups or pull them for restore.

**Comment by loomchild** [comment]
Heh, sure. I even did something similar before. Another solution would be to use a storage driver that stores data somewhere - maybe it's just a configuration issue?

**Comment by loomchild** [comment]
Take a look at available [volume drivers](https://docs.docker.com/registry/storage-drivers/) - it seems like there's an [S3 driver](https://docs.docker.com/registry/storage-drivers/s3/) as well - although I haven't tested it, I don't know how stable it is.

I prefer to keep this doing one thing well, than doing everything, so I will close this issue.

**Comment by JDiPierro** [comment]
The S3 driver is part of the [Registry storage drivers](https://docs.docker.com/registry/storage-drivers/). I don't believe those are available as volume drivers. I see a volume plugin on [this list](https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins) that looks like it has S3 support. I feel like going that route kind of invalidates the need for this project a bit: I don't want to use S3 as the backend for my storage, but I would like to write my backups there to have them off site and for zipped for maximum portability.

That said I do like the one-thing mentality so I might work on an extension of this that adds that capability :)

**Comment by loomchild** [comment]
Ah, you are right, I was too quick.

**Comment by loomchild** [comment]
In the spirit of unix tools doing one thing right - new addition of [backup to STDOUT](https://github.com/loomchild/volume-backup#backup-to-standard-output) and [restore from STDIN](https://github.com/loomchild/volume-backup#restore-from-standard-input) might interest you. Maybe it's possible to integrate it with S3 if it accepts data from streams.

**Comment by loomchild** [comment]
In the spirit of unix tools doing one thing right - new addition of [backup to STDOUT](https://github.com/loomchild/volume-backup#backup-to-standard-output) and [restore from STDIN](https://github.com/loomchild/volume-backup#restore-from-standard-input) might interest you. Maybe it's possible to integrate it with S3 if it accepts data from streams.

**Comment by mbejda** [comment]
I have been storing to S3 using `cp` like so : 
`docker run -v wp_content:/volume --rm loomchild/volume-backup backup | aws s3 cp - s3://<bucket>/backup/contents/wp_content.tar.bz2`. The container outputs an annoying 
`
Options:
  -c <algorithm> chooose compression algorithm: bz2 (default), gz and 0 (none)
  -e <glob> exclude files or directories (only for backup operation)
`
but nonetheless the contents get saved to S3 just fine.

**Comment by mbejda** [comment]
This may help someone in the future. 
Here is an example of using it with S3 streaming capability. 


**Create a backup and stream it to S3:**
```
docker run -v [your volume]:/volume --rm loomchild/volume-backup backup -| aws s3 cp - s3://[s3bucket]/contents.tar.bz2
```
**Restore from S3**
```
aws s3 cp s3://[s3bucket]/contents.tar.bz2 -| docker run -i -v [your volume]:/volume --rm loomchild/volume-backup restore -
```

Those commands assume you have correct IAM permissions to interact with an S3 bucket. If you get a kickback you may need to pass access token and access key parameters.
