### ISSUE TITLE
One-minute sleep should no longer be necessary

### ISSUE THREAD

**Issue by holdenweb** [loomchild/volume-backup#30]
Issue https://github.com/docker/compose/pull/4738 has been closed as no longer reproducible, so I presume this means the one-second sleep is no longer required.

**Comment by loomchild** [comment]
You are probably right. I will try to test it when I have some time - feel free to do it if you can.

**Comment by loomchild** [comment]
Done, removed the one second delay as I cannot reproduce the docker-compose issue anymore.
