### ISSUE TITLE
Fails to Run on Raspberry Pi 4 (aarch64)

### ISSUE THREAD

**Issue by ProfessorManhattan** [loomchild/volume-backup#32]
Hey, I think this Dockerfile might not work on Raspberry Pi 4. The architecture is aarch64. When I run:

```
docker run -v verdaccio_verdaccio:/volume -v /tmp:/backup --rm loomchild/volume-backup backup test
```
OR
```
docker run -v verdaccio_verdaccio:/volume -v /tmp:/backup --rm loomchild/volume-backup backup -> verdaccio_verdaccio.tar.bz2
```
I get the following error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

Any idea on how to get this working? If not, any idea on what alternative I should be using?

**Comment by ProfessorManhattan** [comment]
Nevermind on this one. It ended up being because I was running verdaccio in a docker-compose.yml set up on aarch64. Apparently, verdaccio does not support aarch64. I found this out by looking at docker-compose logs -f

**Comment by loomchild** [comment]
Ah, glad you resolved it, thanks for following up.
