### ISSUE TITLE
Multi-arch builds for arm64

### ISSUE THREAD

**Issue by akutruff** [loomchild/volume-backup#34]
It would be great if multiple arches were available in the package.   I forked and built my own here: [akutruff/volume-backup](https://hub.docker.com/repository/registry-1.docker.io/akutruff/volume-backup/settings)  

I built on WSL2 using buildx.   First I created a builder, and boostrapped it:
```
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
```

Then I built it:
```
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t akutruff/volume-backup:latest --push .
```

Tested on arm64.

Side note:  This is an amazing little utility!  Very clever implementation and nicely flexible.  Good work!

**Comment by caic** [comment]
Hi!

+1 to your side note :)

I tried this in my RPI4 (arm/v7) but in Alpine 3.13 arm/v7 there is [an issue with network-access](https://github.com/alpinelinux/docker-alpine/issues/135).

Changing FROM in Dockerfile to previous Alpine version worked for me:

`FROM alpine:3.12`

Tested in a RPI4.

Cheers.

**Comment by loomchild** [comment]
Hi, thanks for reporting, I will look into this ASAP.

**Comment by loomchild** [comment]
I was able to build multi-arch package locally, but I wonder how to do it on dockerhub. Could you offer some advice please? (I found this article https://cstan.io/?p=11870&lang=en, but not sure if it's up to date as the commands didn't work for me)
