### ISSUE TITLE
Stop containers before backup

### ISSUE THREAD

**Issue by mouzzampk2014-zz** [loomchild/volume-backup#37]
Hi, would be great if script automatically stop all containers and run the backup and restart the containers?

Thank you

**Comment by loomchild** [comment]
Hi, thanks for a suggestion, but unfortunately it's out of scope of this simple project. 

The script operates from within Docker container, where I don't have access to the docker process, so I can't stop the containers. You'd need to write a wrapper script for the host that stops the containers and runs my script.
