### ISSUE TITLE
pbzip2 support?

### ISSUE THREAD

**Issue by gabrielke** [loomchild/volume-backup#41]
Would it be possible to support pbzip2 (plus maybe nice and ionice)?

**Comment by loomchild** [comment]
Sorry, pbzip2 is not available as Alpine package, which complicates things, as it would need to be built from source.

I don't intend to maintain such a package, unless you really need it, and can provide a PR.

**Comment by gabrielke** [comment]
Hi,

I found this gist on github for that: 

https://gist.github.com/stefanthoss/f1a2128eb054528feb05c4006a7efaa0

Would you accept as contribution if I "solve" this issue with a pull request based on this gist?
I will check it for functionality of course.

**Comment by loomchild** [comment]
Yeah, I saw this one. I would really prefer an official pbzip2 package for Alpine, so I prefer to wait for that. Perhaps consider using `zstd` algorithm, which is parallel AFAIK (I am not an expert though)?

**Comment by loomchild** [comment]
What about using `pigz` (it's available in Alpine)?

**Comment by loomchild** [comment]
(I just added pigz. it offers lower compression, but is much faster than bzip2)

**Comment by loomchild** [comment]
I am closing this issue as won't fix, I can revisit it once official pbzip2 package becomes available.
