### ISSUE TITLE
Question: Why use `cat file |` instead of `< file`?

### ISSUE THREAD

**Issue by seyfahni** [loomchild/volume-backup#44]
The Readme suggests using `cat archive | docker ... -` to restore backups, but that is another process call, wouldn't it be more efficient to just use `docker ... - <archive` instead?
While it does work (I only tested with small backups) I'm not quite sure myself if there are major downsides to it.

**Comment by loomchild** [comment]
Yes, you are right, it probably would be more efficient. I wrote it with cat out of habit and for readability. Would you be able to prepare a benchmark to illustrate that there's a difference?

**Comment by loomchild** [comment]
Never mind, I think it will be even more readable with `<` at the end, since it's similar to normal restore syntax and backup syntax. I will change it when I have a bit of time. Thanks for your suggestion.

**Comment by loomchild** [comment]
I have made the changes to README and tested them. Thank you!
