### ISSUE TITLE
automatic backup?

### ISSUE THREAD

**Issue by jadster** [loomchild/volume-backup#5]
is there any reason this couldn't be run from cron on a regular basis for an automatic backup?

**Comment by loomchild** [comment]
It's necessary to stop the container first to avoid any writes during the backup process / incoherent data (cold backup), so if you can do it in your cron I see no reason why not (in fact this utility was written for regular backups in [Puffin](https://github.com/puffinrocks/puffin/)).

**Comment by loomchild** [comment]
Closing, feel free to re-open if you have more questions.
