### ISSUE TITLE
Backup of large volume fails with bzip2 error "short write"

### ISSUE THREAD

**Issue by katanacrimson** [loomchild/volume-backup#8]
I'm currently trying to write a backup wrapper around this docker image (which has been very helpful, thanks!) and have started to run into a roadblock - when it gets to backing up my gitlab_data volume (which weighs in at 4.025GB, per `docker system df -v`), I run into this:

```
Jan 14 14:26:13 nomad volume-backup.sh[9945]: bzip2: short write
Jan 14 14:26:13 nomad volume-backup.sh[9945]: tar: write error: Broken pipe
```

from which it turns into an unrecoverable failure and the backup cannot be completed.  I'm not sure if it's just too many file handles or what; the only thing of relevance that I have found so far is this:

https://askubuntu.com/questions/835226/error-with-gzip-while-used-along-with-tar

**Comment by katanacrimson** [comment]
Appears that the destination filesystem was full - nvm me!

**Comment by loomchild** [comment]
OK, no problem. Thanks for closing.
